language: ruby
services:
  - redis-server
rvm:
  - jruby-19mode
  - rbx-2
  - 2.0.0
  - 2.1
  - 2.2
matrix:
  allow_failures:
    - rvm: rbx-2
before_install:
  # Only use 1 job until Travis fixes the rbx --jobs issue.
  - if [ "$TRAVIS_RUBY_VERSION" == "rbx-2" ] ; then export BUNDLE_JOBS=1 ; fi
